# Basic
title: Joan Rocky
subtitle: 「人生只有一次，没有彩排」

description: 嗨，我是Rocky，歡迎來到我的個人博客.

welcome_message: <a href="https://github.com/Lsd110" target="_blank">關注科技與人文</a>

creator: <a href="http://onev.cat">@onevcat</a>

url: "https://lsd110.github.io/vno-jekyll/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 简历, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: 订阅, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: lsd_Fr
    # duoshuo: 
    
# Social
social:
    weibo: onevcat
    github: LSD110
    twitter: onevcat
    mail: 1106752281@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
